version: "3.8"

services:
  app:
    build:
      target: node_development
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - EXEC_ENV=development

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prompt-ia
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local